// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haghrkkfadayhirldynh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZ2hya2tmYWRheWhpcmxkeW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDUxODcsImV4cCI6MjA2OTI4MTE4N30.7mxSdaoHy9zD67LI9IkeMvrUuWwi14kGfW5sUoK9G_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});